CREATE DATABASE Sanyaritu;
USE Sanyaritu;

CREATE TABLE DEPARTMENT(
    DEPTNO INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50) NOT NULL,
    CURR_PROJECTS INT,
    POSITIONS VARCHAR(50),
    BUDGET INT
);
CREATE TABLE EMPLOYEE(
    EMPID INT PRIMARY KEY,
    ENAME VARCHAR(50) NOT NULL,
    E_PHONE_NO VARCHAR(15),
    EDATE DATE,
    DEPTNO INT,
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
);
CREATE TABLE SALARY(
    EMPID INT PRIMARY KEY,
    ESAL INT,
    COMMISSION BOOLEAN,
    ANNUAL_INCREMENT_PERCENT INT,
    TAX_DEDUCTION INT,
    FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(EMPID)
);
CREATE TABLE PROJECTS(
    PID INT PRIMARY KEY,
    PNAME VARCHAR(50),
    DEADLINE DATE,
    PROJECT_HEAD VARCHAR(50),
    SUBMISSION_TYPE VARCHAR(50),
    DEPTNO INT,
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
);
CREATE TABLE ATTENDANCE(
    ATTEND_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPID INT,
    DATE_OF_ATTENDANCE DATE,
    CHECK_IN_TIME TIME,
    CHECK_OUT_TIME TIME,
    ATTENDED BOOLEAN,
    FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID)
);
